name: Code Quality Checks

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: Shell Script Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
      
    - name: Run syntax check
      run: make syntax-check
      
    - name: Run ShellCheck linting
      run: make lint
      
    - name: Run security scan
      run: make security-scan

  lua-lint:
    name: Lua Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"
        
    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v5
      
    - name: Install luacheck
      run: luarocks install luacheck
      
    - name: Run luacheck
      run: |
        luacheck --version
        luacheck . --codes --ranges
      env:
        LUA_PATH: "/home/runner/.luarocks/share/lua/5.4/?.lua;/home/runner/.luarocks/share/lua/5.4/?/init.lua;;"
        LUA_CPATH: "/home/runner/.luarocks/lib/lua/5.4/?.so;;"